"""
On Wikipedia, cities are listed as <city name>, <state name>, so states
abbreviations should be changed to their full name. This is just a function
that uses the STATE dict to lookup known abbreviations and return the name
when there is a match. This mostly exists so that other files don't have to
have this ugly bit of code.
"""

STATE = {
    "AK": "Alaska",
    "AL": "Alabama",
    "AR": "Arkansas",
    "AZ": "Arizona",
    "Ala.": "Alabama",
    "Alas.": "Alaska",
    "Alaska": "Alaska",
    "Ariz.": "Arizona",
    "Ark.": "Arkansas",
    "Az.": "Arizona",
    "CA": "California",
    "CO": "Colorado",
    "CT": "Connecticut",
    "Ca.": "California",
    "Cal.": "California",
    "Calif.": "California",
    "Col.": "Colorado",
    "Colo.": "Colorado",
    "Conn.": "Connecticut",
    "Ct.": "Connecticut",
    "D.C.": "District of Columbia",
    "DC": "District of Columbia",
    "DE": "Delaware",
    "De.": "Delaware",
    "Del.": "Delaware",
    "FL": "Florida",
    "Fl.": "Florida",
    "Fla.": "Florida",
    "Flor.": "Florida",
    "GA": "Georgia",
    "Ga.": "Georgia",
    "H.I.": "Hawaii",
    "HI": "Hawaii",
    "Hawaii": "Hawaii",
    "IA": "Iowa",
    "ID": "Idaho",
    "IL": "Illinois",
    "IN": "Indiana",
    "Ia.": "Iowa",
    "Id.": "Idaho",
    "Ida.": "Idaho",
    "Idaho": "Idaho",
    "Il.": "Illinois",
    "Ill's": "Illinois",
    "Ill.": "Illinois",
    "Ills.": "Illinois",
    "In.": "Indiana",
    "Ind.": "Indiana",
    "Ioa.": "Iowa",
    "Iowa": "Iowa",
    "KS": "Kansas",
    "KY": "Kentucky",
    "Ka.": "Kansas",
    "Kan.": "Kansas",
    "Kans.": "Kansas",
    "Ken.": "Kentucky",
    "Kent.": "Kentucky",
    "Ks.": "Kansas",
    "Ky.": "Kentucky",
    "LA": "Louisiana",
    "La.": "Louisiana",
    "MA": "Massachusetts",
    "MD": "Maryland",
    "ME": "Maine",
    "MI": "Michigan",
    "MN": "Minnesota",
    "MO": "Missouri",
    "MS": "Mississippi",
    "MT": "Montana",
    "Maine": "Maine",
    "Mass.": "Massachusetts",
    "Md.": "Maryland",
    "Me.": "Maine",
    "Mich.": "Michigan",
    "Minn.": "Minnesota",
    "Miss.": "Mississippi",
    "Mn.": "Minnesota",
    "Mo.": "Missouri",
    "Mont.": "Montana",
    "N. Car.": "North Carolina",
    "N. Dak.": "North Dakota",
    "N. Mex.": "New Mexico",
    "N. York": "New York",
    "N.C.": "North Carolina",
    "N.D.": "North Dakota",
    "N.H.": "New Hampshire",
    "N.J.": "New Jersey",
    "N.M.": "New Mexico",
    "N.Y.": "New York",
    "NC": "North Carolina",
    "ND": "North Dakota",
    "NE": "Nebraska",
    "NH": "New Hampshire",
    "NJ": "New Jersey",
    "NM": "New Mexico",
    "NV": "Nevada",
    "NY": "New York",
    "Neb.": "Nebraska",
    "Nebr.": "Nebraska",
    "Nev.": "Nevada",
    "New M.": "New Mexico",
    "NoDak": "North Dakota",
    "Nv.": "Nevada",
    "O.": "Ohio",
    "OH": "Ohio",
    "OK": "Oklahoma",
    "OR": "Oregon",
    "Oh.": "Ohio",
    "Ohio": "Ohio",
    "Ok.": "Oklahoma",
    "Okla.": "Oklahoma",
    "Or.": "Oregon",
    "Ore.": "Oregon",
    "Oreg.": "Oregon",
    "PA": "Pennsylvania",
    "Pa.": "Pennsylvania",
    "Penn.": "Pennsylvania",
    "Penna.": "Pennsylvania",
    "R. Isl.": "Rhode Island",
    "R.I.": "Rhode Island",
    "R.I. & P.P.": "Rhode Island",
    "RI": "Rhode Island",
    "S. Car.": "South Carolina",
    "S. Dak.": "South Dakota",
    "S.C.": "South Carolina",
    "S.D.": "South Dakota",
    "SC": "South Carolina",
    "SD": "South Dakota",
    "SoDak": "South Dakota",
    "TN": "Tennessee",
    "TX": "Texas",
    "Tenn.": "Tennessee",
    "Tex.": "Texas",
    "Texas": "Texas",
    "Tx.": "Texas",
    "UT": "Utah",
    "Ut.": "Utah",
    "Utah": "Utah",
    "VA": "Virginia",
    "VT": "Vermont",
    "Va.": "Virginia",
    "Virg.": "Virginia",
    "Vt.": "Vermont",
    "W. Va.": "West Virginia",
    "W. Virg.": "West Virginia",
    "W.V.": "West Virginia",
    "W.Va.": "West Virginia",
    "WA": "Washington",
    "WI": "Wisconsin",
    "WV": "West Virginia",
    "WY": "Wyoming",
    "Wa.": "Washington",
    "Wash.": "Washington",
    "Wash. D.C.": "District of Columbia",
    "Wi.": "Wisconsin",
    "Wis.": "Wisconsin",
    "Wisc.": "Wisconsin",
    "Wn.": "Washington",
    "Wy.": "Wyoming",
    "Wyo.": "Wyoming"
}


def abbr_to_full(abbr):
    return STATE.get(abbr, abbr)
